### ISSUE TITLE
3 tests fail

### ISSUE THREAD

**Issue by imartayan** [suecharo/tataki#9]
When trying to run `cargo test` on my laptop, 3 of them are failing:
- `can_output_to_file`
- `output_in_json_and_can_keep_cache`
- `can_run_cwl`

<details>
<summary>Detailed log</summary>

```
running 11 tests
test can_dry_run ... ok
test can_limit_the_number_of_output_records ... ok
test can_be_quiet ... ok
test can_be_verbose ... ok
test can_use_config_file ... ok
test can_read_entirety_of_input_file ... ok
test can_output_to_file ... FAILED
test output_in_csv ... ok
test output_in_json_and_can_keep_cache ... FAILED
test output_in_yaml ... ok
test can_run_cwl ... FAILED

failures:

---- can_output_to_file stdout ----
thread 'can_output_to_file' panicked at /rustc/4bc39f028d14c24b04dd17dc425432c6ec354536/library/core/src/ops/function.rs:250:5:
Unexpected failure.
code=1
stderr=``````
[2024-07-16T13:56:49Z INFO  tataki::module] tataki started
[2024-07-16T13:56:49Z INFO  tataki::module] Created temporary directory: /var/folders/vw/9zmjkym910n1x87lytxt__1h0000gn/T/tataki_2024-0716-095649_uLeOWB
[2024-07-16T13:56:49Z INFO  tataki::module] Processing input: ./inputs/toy.sam
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser empty
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser bam
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser bcf
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser bed
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser cram
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser fasta
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser fastq
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser gff3
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser gtf
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser sam
[2024-07-16T13:56:49Z INFO  tataki::module] Detected!! sam
[2024-07-16T13:56:49Z INFO  tataki::module] Processing input: ./inputs/toy.fa
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser empty
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser bam
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser bcf
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser bed
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser cram
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser fasta
[2024-07-16T13:56:49Z INFO  tataki::module] Detected!! fasta
[2024-07-16T13:56:49Z INFO  tataki::module] Deleting temporary directory: /var/folders/vw/9zmjkym910n1x87lytxt__1h0000gn/T/tataki_2024-0716-095649_uLeOWB
[2024-07-16T13:56:49Z INFO  tataki::module] Writing the result to ./cache_dir/output.csv
Error: No such file or directory (os error 2)
```
```
command=`cd "tests/" && "/Users/igor/Dev/tataki/target/debug/tataki" "./inputs/toy.sam" "./inputs/toy.fa" "-o" "./cache_dir/output.csv"`
code=1
stdout=""
stderr=```
[2024-07-16T13:56:49Z INFO  tataki::module] tataki started
[2024-07-16T13:56:49Z INFO  tataki::module] Created temporary directory: /var/folders/vw/9zmjkym910n1x87lytxt__1h0000gn/T/tataki_2024-0716-095649_uLeOWB
[2024-07-16T13:56:49Z INFO  tataki::module] Processing input: ./inputs/toy.sam
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser empty
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser bam
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser bcf
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser bed
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser cram
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser fasta
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser fastq
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser gff3
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser gtf
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser sam
[2024-07-16T13:56:49Z INFO  tataki::module] Detected!! sam
[2024-07-16T13:56:49Z INFO  tataki::module] Processing input: ./inputs/toy.fa
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser empty
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser bam
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser bcf
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser bed
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser cram
[2024-07-16T13:56:49Z INFO  tataki::parser] Invoking parser fasta
[2024-07-16T13:56:49Z INFO  tataki::module] Detected!! fasta
[2024-07-16T13:56:49Z INFO  tataki::module] Deleting temporary directory: /var/folders/vw/9zmjkym910n1x87lytxt__1h0000gn/T/tataki_2024-0716-095649_uLeOWB
[2024-07-16T13:56:49Z INFO  tataki::module] Writing the result to ./cache_dir/output.csv
Error: No such file or directory (os error 2)
```

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- output_in_json_and_can_keep_cache stdout ----
thread 'output_in_json_and_can_keep_cache' panicked at /rustc/4bc39f028d14c24b04dd17dc425432c6ec354536/library/core/src/ops/function.rs:250:5:
Unexpected failure.
code=1
stderr=``````
[2024-07-16T13:56:49Z INFO  tataki::module] tataki started
Error: No such file or directory (os error 2) at path \"/Users/igor/Dev/tataki/tests/./cache_dir/tataki_2024-0716-095649_ZBt8Cr\"
```
```
command=`cd "tests/" && "/Users/igor/Dev/tataki/target/debug/tataki" "./inputs/toy.sam" "https://github.com/sapporo-wes/tataki/raw/main/tests/inputs/toy.fa" "--cache-dir" "./cache_dir/" "-f" "json"`
code=1
stdout=""
stderr=```
[2024-07-16T13:56:49Z INFO  tataki::module] tataki started
Error: No such file or directory (os error 2) at path \"/Users/igor/Dev/tataki/tests/./cache_dir/tataki_2024-0716-095649_ZBt8Cr\"
```



---- can_run_cwl stdout ----
thread 'can_run_cwl' panicked at tests/integration_tests.rs:248:5:
assertion `left == right` failed
  left: [StringRecord(["./inputs/toy.py", "", "", "", ""]), StringRecord(["./inputs/toy.fa", "", "", "", ""])]
 right: [StringRecord(["./inputs/toy.py", "http://edamontology.org/format_3996", "Python script", "", ""]), StringRecord(["./inputs/toy.fa", "", "", "", ""])]


failures:
    can_output_to_file
    can_run_cwl
    output_in_json_and_can_keep_cache

test result: FAILED. 8 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.73s
```
</details>

**Comment by fmaccha** [comment]
I think the errors are likely occurring because the prerequisite directories do not exist. I plan to add code to check for the existence of these directories.

Thanks for submitting this issue!

**Comment by fmaccha** [comment]
@imartayan I could not determine why `can_run_cwl` failed. Could you please run the following command in the `<repo root>/tests` and show me the output? I suspect that the issues might be whether `docker` is in the `$PATH`.

```sh
cargo run -- ./inputs/toy.py ./inputs/toy.fa -c ./conf/run_cwl_test.conf  -v
```

**Comment by imartayan** [comment]
Here is the output for this command.

<details>
<summary>Output</summary>

```
[2024-07-23T00:11:09Z INFO  tataki::module] tataki started
[2024-07-23T00:11:09Z DEBUG tataki::module] Args: Args { input: ["./inputs/toy.py", "./inputs/toy.fa"], output: None, output_format: Csv, yaml: false, json: false, tsv: false, cache_dir: None, conf: Some("./conf/run_cwl_test.conf"), tidy: false, no_decompress: false, num_records: 100000, dry_run: false, verbose: true, quiet: false }
[2024-07-23T00:11:09Z DEBUG tataki::module] Output format: Csv
[2024-07-23T00:11:09Z INFO  tataki::module] Created temporary directory: /var/folders/vw/9zmjkym910n1x87lytxt__1h0000gn/T/tataki_2024-0722-201109_EuC0p6
[2024-07-23T00:11:09Z INFO  tataki::module] Processing input: ./inputs/toy.py
[2024-07-23T00:11:09Z DEBUG tataki::source] Comressed format of the input is not inferrable, or the input is not compressed. Parsing the input as is.
[2024-07-23T00:11:09Z INFO  tataki::parser] Invoking parser empty
[2024-07-23T00:11:09Z DEBUG tataki::module] Module "empty" failed. Reason:
    The file is not empty
[2024-07-23T00:11:09Z INFO  tataki::ext_tools] Invoking ext_tools ./cwl/python.cwl
[2024-07-23T00:11:09Z DEBUG tataki::ext_tools] The path of the docker command in your environment: "/usr/local/bin/docker".
[2024-07-23T00:11:09Z DEBUG tataki::ext_tools] The docker image 'python:3.11.8-alpine3.19' is specified in the CWL file: /Users/igor/Dev/tataki/tests/cwl/python.cwl
[2024-07-23T00:11:10Z WARN  tataki::module] An error occurred while trying to invoke the './cwl/python.cwl' module. Reason:
    Failed to run 'cwl-inspector' image:
    WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
    /usr/bin/cwl/inspector.rb:48:in `docker_requirement': Docker required but not found (CWLInspectionError)
    	from /usr/bin/cwl/inspector.rb:696:in `parse_object'
    	from /usr/bin/cwl/inspector.rb:592:in `block in parse_inputs'
    	from /usr/bin/cwl/inspector.rb:591:in `map'
    	from /usr/bin/cwl/inspector.rb:591:in `parse_inputs'
    	from /usr/bin/cwl/inspector.rb:1083:in `<main>'

[2024-07-23T00:11:10Z INFO  tataki::module] Processing input: ./inputs/toy.fa
[2024-07-23T00:11:10Z DEBUG tataki::source] Comressed format of the input is not inferrable, or the input is not compressed. Parsing the input as is.
[2024-07-23T00:11:10Z INFO  tataki::parser] Invoking parser empty
[2024-07-23T00:11:10Z DEBUG tataki::module] Module "empty" failed. Reason:
    The file is not empty
[2024-07-23T00:11:10Z INFO  tataki::ext_tools] Invoking ext_tools ./cwl/python.cwl
[2024-07-23T00:11:10Z DEBUG tataki::ext_tools] The path of the docker command in your environment: "/usr/local/bin/docker".
[2024-07-23T00:11:10Z DEBUG tataki::ext_tools] The docker image 'python:3.11.8-alpine3.19' is specified in the CWL file: /Users/igor/Dev/tataki/tests/cwl/python.cwl
[2024-07-23T00:11:11Z WARN  tataki::module] An error occurred while trying to invoke the './cwl/python.cwl' module. Reason:
    Failed to run 'cwl-inspector' image:
    WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
    /usr/bin/cwl/inspector.rb:48:in `docker_requirement': Docker required but not found (CWLInspectionError)
    	from /usr/bin/cwl/inspector.rb:696:in `parse_object'
    	from /usr/bin/cwl/inspector.rb:592:in `block in parse_inputs'
    	from /usr/bin/cwl/inspector.rb:591:in `map'
    	from /usr/bin/cwl/inspector.rb:591:in `parse_inputs'
    	from /usr/bin/cwl/inspector.rb:1083:in `<main>'

[2024-07-23T00:11:11Z INFO  tataki::module] Deleting temporary directory: /var/folders/vw/9zmjkym910n1x87lytxt__1h0000gn/T/tataki_2024-0722-201109_EuC0p6
File Path,Edam ID,Label,Decompressed ID,Decompressed Label
./inputs/toy.py,,,,
./inputs/toy.fa,,,,
```
</details>

Looking at the logs, it seems to be related to the arm64 architecture of my laptop (I'm using an M1 Mac).

**Comment by fmaccha** [comment]
Thank you for the output, and sorry for the delayed response.

In the cwl extension mode, when creating a docker command line with `cwl-inspector` image for running cwl file, tataki uses the local `docker` binary. It seems the error occurred due to the architecture mismatch of this binary. 
It worked successfully when I downloaded the Arm binary from [here](https://download.docker.com/linux/static/stable/aarch64/) and replaced it.

As a workaround for now, I'm planning to disable the cwl extension mode tests on M1 Mac.

Currently M1 Mac is not supported, but we are planning to support it. At that time, we will properly fix this issue.
